### PR TITLE
Small fix to trialized time series view

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@h-mayorquin 

Small fix for if the edges of the times overlap slightly, such as the end of one trial is equal to the start of the next (otherwise `h5py` complains that the data access isn't strictly increasing)

### CODE REVIEW

**Comment by h-mayorquin** [comment]
It is interesting. This error did not surface to me because I was testing files in memory. That is, I ran some tests on a file with overlap that should have risen this error but they did not. They do raise the error if I write the nwbfile to disk and then read it and try again.

**Comment by h-mayorquin** [comment]
Turns out that the redundancy is needed when we add the control that Ben requested. I instead implemented another approach based on `np.searchsorted` on the last commit.  Can you check if it works for you? It works for me saving and loading the data.

**Review by h-mayorquin — COMMENTED** [review]
Turns out that the redundancy is needed when we add the control that Ben requested. I instead implemented another approach based on np.searchsorted on the last commit. Can you check if it works for you? It works for me saving and loading the data.

**Comment by CodyCBakerPhD** [comment]
Yup, current branch of `trialized_time_series_facet` works for me 👍

**Pull request closed without merging**
